import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Quicksand } from 'next/font/google'

const inter = Quicksand({ subsets: ['latin'] })

export const metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
